In [1]:
import numpy as np

data = np.genfromtxt("/Users/curtis/Uni Linköping/TNM098_Advanced_Visual_Data_Analysis/Labs/Lab1/CoinToss.csv", delimiter=',', dtype='int',)

print (data)


[[1 1 1 ..., 0 1 1]
 [0 1 1 ..., 1 0 0]
 [1 0 0 ..., 0 1 0]
 ..., 
 [0 0 0 ..., 0 1 1]
 [1 1 1 ..., 1 1 0]
 [0 1 0 ..., 0 1 0]]


In [2]:
print (data[0])
    

[1 1 1 1 1 1 1 1 0 1 0 0 1 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 0 0 0 1 1 1 0 1
 0 0 1 1 1 1 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 1 0 1 0 0 1
 0 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 1 1 1 1 0 1 0 1 0 0
 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 0 1 1 1 1 0 0 0 0 0 0 1 0 1 0 1 0 0
 1 0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 1 0 1
 0 0 0 1 1 0 1 0 1 1 1 1 0 1 1]


In [69]:
list_a = [111,0,3,1,111,0,3,1,111,0,3,1] 
print (list_a)

[111, 0, 3, 1, 111, 0, 3, 1, 111, 0, 3, 1]


In [83]:
#get the longest sequence length
def guess_seq_len(seq):
    seq_length = 1
    max_len = len(seq) // 2
    for x in range(2, max_len):
        if (seq[0:x] == seq[x:2*x]).all() :
            return x

    return seq_length

#list_a = [111,0,3,1,111,0,3,1,111,0,3,1] 
#list_b = [67,4,67,4,67,4,67,4,2,9,0]
#list_c = [1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,23,18,10]

#print (guess_seq_len(list_a))
#print (guess_seq_len(list_b))
#print (guess_seq_len(list_c))
#print (guess_seq_len(range(500)))
i=0
for item in data:
    print ("max sequence length for data iteam "+ str(i) + ": ") 
    print(guess_seq_len(item))
    i=i+1


max sequence length for data iteam 0: 
2
max sequence length for data iteam 1: 
1
max sequence length for data iteam 2: 
1
max sequence length for data iteam 3: 
1
max sequence length for data iteam 4: 
1
max sequence length for data iteam 5: 
3
max sequence length for data iteam 6: 
1
max sequence length for data iteam 7: 
4
max sequence length for data iteam 8: 
3
max sequence length for data iteam 9: 
1
max sequence length for data iteam 10: 
4
max sequence length for data iteam 11: 
1
max sequence length for data iteam 12: 
1
max sequence length for data iteam 13: 
2
max sequence length for data iteam 14: 
2
max sequence length for data iteam 15: 
2
max sequence length for data iteam 16: 
2
max sequence length for data iteam 17: 
4
max sequence length for data iteam 18: 
1
max sequence length for data iteam 19: 
1
max sequence length for data iteam 20: 
1
max sequence length for data iteam 21: 
3
max sequence length for data iteam 22: 
1
max sequence length for data iteam 23: 
1
ma

In [82]:
#get the number of occurences of the longest sequence
def guess_seq_occ(seq):
    seq_occ = 0
    max_len = len(seq) // 2
    for x in range(2, max_len):
        if (seq[0:x] == seq[x:2*x]).all() :
            seq_occ = x

    return seq_occ

#list_a = [111,0,3,1,111,0,3,1,111,0,3,1] 
#list_b = [67,4,67,4,67,4,67,4,2,9,0]
#list_c = [1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,23,18,10]

#print (guess_seq_occ(list_a))
#print (guess_seq_occ(list_b))
#print (guess_seq_occ(list_c))
#print (guess_seq_occ(range(500)))

i=0
for item in data:
    print ("number of occurences for max sequence for data iteam "+ str(i) + ": ") 
    print(guess_seq_occ(item))
    i=i+1

number of occurences for max sequence for data iteam 0: 
4
number of occurences for max sequence for data iteam 1: 
0
number of occurences for max sequence for data iteam 2: 
0
number of occurences for max sequence for data iteam 3: 
0
number of occurences for max sequence for data iteam 4: 
0
number of occurences for max sequence for data iteam 5: 
3
number of occurences for max sequence for data iteam 6: 
0
number of occurences for max sequence for data iteam 7: 
4
number of occurences for max sequence for data iteam 8: 
3
number of occurences for max sequence for data iteam 9: 
0
number of occurences for max sequence for data iteam 10: 
4
number of occurences for max sequence for data iteam 11: 
0
number of occurences for max sequence for data iteam 12: 
0
number of occurences for max sequence for data iteam 13: 
2
number of occurences for max sequence for data iteam 14: 
2
number of occurences for max sequence for data iteam 15: 
2
number of occurences for max sequence for data ite

In [87]:
#get the longest sequence
def guess_seq(seq):
    found_seq = None
    max_len = len(seq) // 2
    for x in range(2, max_len):
        if (seq[0:x] == seq[x:2*x]).all() :
            found_seq = seq[0:x]
            return found_seq

    return found_seq

#list_a = [111,0,3,1,111,0,3,1,111,0,3,1] 
#list_b = [67,4,67,4,67,4,67,4,2,9,0]
#list_c = [1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,23,18,10]

#print (guess_seq_len(list_a))
#print (guess_seq_len(list_b))
#print (guess_seq_len(list_c))
#print (guess_seq_len(range(500)))
i=0
for item in data:
    print ("max sequence for data iteam "+ str(i) + ": ") 
    print(guess_seq(item))
    i=i+1

max sequence for data iteam 0: 
[1 1]
max sequence for data iteam 1: 
None
max sequence for data iteam 2: 
None
max sequence for data iteam 3: 
None
max sequence for data iteam 4: 
None
max sequence for data iteam 5: 
[1 0 1]
max sequence for data iteam 6: 
None
max sequence for data iteam 7: 
[0 1 1 1]
max sequence for data iteam 8: 
[0 1 1]
max sequence for data iteam 9: 
None
max sequence for data iteam 10: 
[1 0 0 0]
max sequence for data iteam 11: 
None
max sequence for data iteam 12: 
None
max sequence for data iteam 13: 
[1 1]
max sequence for data iteam 14: 
[1 1]
max sequence for data iteam 15: 
[1 1]
max sequence for data iteam 16: 
[1 1]
max sequence for data iteam 17: 
[0 0 1 1]
max sequence for data iteam 18: 
None
max sequence for data iteam 19: 
None
max sequence for data iteam 20: 
None
max sequence for data iteam 21: 
[1 0 1]
max sequence for data iteam 22: 
None
max sequence for data iteam 23: 
None
max sequence for data iteam 24: 
None
max sequence for data iteam 25:

In [99]:
#get the longest sequence
def guess_seq(seq):
    found_seq = None
    max_len = len(seq) // 2
    for x in range(2, max_len):
        if (seq[0:x] == seq[x:2*x]).all() :
            found_seq = seq[0:2*x]
            return found_seq
    return found_seq

#get longest sequence length
def guess_seq_len(seq):
    seq_length = 1
    max_len = len(seq) // 2
    for x in range(2, max_len):
        if (seq[0:x] == seq[x:2*x]).all() :
            return x
    return seq_length

#get the number of occurences of the longest sequence
def guess_seq_occ(seq):
    seq_occ = 0
    max_len = len(seq) // 2
    for x in range(2, max_len):
        if (seq[0:x] == seq[x:2*x]).all() :
            seq_occ = seq_occ + 1
    return seq_occ

i=0
for item in data:
    print ("data item " + str(i) + ":")
    print ("    longest sequence: " + str(guess_seq(item)))
    print ("    longest sequence length: " + str(guess_seq_len(item)))
    print ("    # of occurences of longest sequence: " + str(guess_seq_occ(item))) 

    i=i+1

data item 0:
    longest sequence: [1 1 1 1]
    longest sequence length: 2
    # of occurences of longest sequence: 3
data item 1:
    longest sequence: None
    longest sequence length: 1
    # of occurences of longest sequence: 0
data item 2:
    longest sequence: None
    longest sequence length: 1
    # of occurences of longest sequence: 0
data item 3:
    longest sequence: None
    longest sequence length: 1
    # of occurences of longest sequence: 0
data item 4:
    longest sequence: None
    longest sequence length: 1
    # of occurences of longest sequence: 0
data item 5:
    longest sequence: [1 0 1 1 0 1]
    longest sequence length: 3
    # of occurences of longest sequence: 1
data item 6:
    longest sequence: None
    longest sequence length: 1
    # of occurences of longest sequence: 0
data item 7:
    longest sequence: [0 1 1 1 0 1 1 1]
    longest sequence length: 4
    # of occurences of longest sequence: 1
data item 8:
    longest sequence: [0 1 1 0 1 1]
    longest 

In [141]:
datastring = np.genfromtxt("/Users/curtis/Uni Linköping/TNM098_Advanced_Visual_Data_Analysis/Labs/Lab1/CoinToss.txt", dtype='str',)



In [167]:
from collections import Counter

def longest_sequence(a):
#    a='11111111010011000101101100101000111010011110010100011001000001100110101001010110100111111100111011100111101010001110000001101001110111100000010101001001000100110100110011110101111110101000110101111011'
    times=20
    for n in range(1,len(a)//times+1)[::-1]:
        substrings=[a[i:i+n] for i in range(len(a)-n+1)]
        freqs=Counter(substrings)
        if freqs.most_common(5)[0][1]>=times:
            seq=freqs.most_common(5)[0][0]
            break
#    print ("     sequence '%s' of length %s occurs %s times"%(seq,n,freqs.most_common(1)[0][1]))
    print(freqs.most_common(5))
    if freqs.most_common(5)[4][1] >=20:
        print ("   HUMAN")
    else:
        print("      COMPUTER")

i=1
for item in datastring:
    print("DATA ITEM " + str(i) + ":")
    longest_sequence(item)
    i=i+1


DATA ITEM 1:
[('111', 30), ('010', 27), ('101', 26), ('001', 25), ('100', 25)]
   HUMAN
DATA ITEM 2:
[('100', 32), ('001', 31), ('110', 28), ('011', 28), ('010', 25)]
   HUMAN
DATA ITEM 3:
[('110', 30), ('011', 30), ('000', 25), ('001', 24), ('101', 24)]
   HUMAN
DATA ITEM 4:
[('110', 29), ('011', 28), ('101', 26), ('111', 26), ('100', 25)]
   HUMAN
DATA ITEM 5:
[('110', 28), ('101', 28), ('011', 28), ('001', 27), ('010', 26)]
   HUMAN
DATA ITEM 6:
[('1101', 20), ('0110', 18), ('0100', 17), ('1011', 16), ('1010', 15)]
      COMPUTER
DATA ITEM 7:
[('0110', 20), ('0011', 19), ('1100', 15), ('1001', 14), ('0001', 13)]
      COMPUTER
DATA ITEM 8:
[('101', 35), ('010', 30), ('110', 28), ('011', 28), ('001', 22)]
   HUMAN
DATA ITEM 9:
[('1101', 22), ('1010', 21), ('1011', 20), ('0101', 19), ('0110', 16)]
      COMPUTER
DATA ITEM 10:
[('101', 31), ('111', 30), ('010', 27), ('110', 26), ('011', 26)]
   HUMAN
DATA ITEM 11:
[('000', 29), ('111', 28), ('001', 26), ('100', 26), ('011', 24)]
   HUM